development:
  adapter: postgresql
  encoding: unicode
  database: quick_bike_dev
  pool: 5
  username: julien
  password: julien

test:
  adapter: postgresql
  encoding: unicode
  database: quick_bike_test
  pool: 5
  username: julien
  password: julien